# fly.toml app configuration file generated for hrconnect on 2023-11-14T22:41:34+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hrconnect"
primary_region = "sin"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
